---
title: "Tips from Tidy Tuesday"
author: "`r Sys.getenv('USERNAME')`"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
## basic settings
knitr::opts_chunk$set(echo = TRUE,
                      message=FALSE,
                      warning=FALSE
                      )

## load common libraries
library(tidyverse)
library(lubridate)
library(scales)
library(plotly)
library(PerformanceAnalytics)

## Reference: R Markdown cheatsheet
## https://www.rstudio.com/wp-content/uploads/2016/03/rmarkdown-cheatsheet-2.0.pdf

## SPECIFIC FOR TIDY TUESDAY
library(tidytuesdayR)

## set default theme for charts
theme_set(theme_bw())

```

## Tips & Techniques {.tabset}

A collection of tidy R tips, tricks, techniques picked up from watching TidyTuesday videos.

* access data easily through tidytuesdayR pkg

```{r IMPORT DATA}
#tt_load('2020-07-07') ## coffee ratings data with info
coffee_ratings <- tt_load('2020-07-07')$coffee_ratings
## save in case not available in future
write_csv(coffee_ratings, 'data/tt_coffee_ratings.csv')

head(coffee_ratings)
```



### General

```{r}

```


### Coffee Ratings

https://www.youtube.com/watch?v=-1x8Kpyndss

```{r COFFEE RATINGS}
## using coffee_ratings imported above
coffee_ratings %>%
  count(species, sort=TRUE)
## count is tidier version of:
table(coffee_ratings$species)

coffee_ratings %>%
  count(variety, sort=TRUE)

## use fct_lump to set limit of items and lump others together
coffee_ratings %>%
  filter(!is.na(variety)) %>%
  count(variety=fct_lump(variety, 10), sort=TRUE)

coffee_lumped <- coffee_ratings %>%
  filter(!is.na(variety),
         total_cup_points > 10) %>%
  mutate(variety=fct_lump(variety, 10), sort=TRUE)

coffee_lumped %>%
  ggplot(aes(x=variety, y=total_cup_points))+geom_boxplot()

coffee_lumped %>%
  ggplot(aes(x=total_cup_points, fill=variety))+
  geom_histogram(binwidth=2)+
  facet_wrap(~variety, scale='free_y')+
  theme(legend.position='none')
```

